# Generated by Django 4.2.30 on 2026-06-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Área')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Área')),
                ('tieneEstudiantes', models.BooleanField(default=True, verbose_name='¿Tiene Estudiantes?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Cargo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Contrato')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Departamento')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('areaPadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='guardia_admin.area', verbose_name='Área / Facultad Padre')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
                'unique_together': {('areaPadre', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Sede')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Física')),
                ('minObreras', models.PositiveIntegerField(default=0, verbose_name='Mínimo de Guardias Obreras')),
                ('minEstudiantiles', models.PositiveIntegerField(default=0, verbose_name='Mínimo de Guardias Estudiantiles')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carné de Identidad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('tipo', models.CharField(choices=[('OBRERO', 'Obrero'), ('ESTUDIANTE', 'Estudiante')], default='OBRERO', max_length=20, verbose_name='Tipo de Guardia')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección de Residencia')),
                ('referencia', models.TextField(blank=True, null=True, verbose_name='Referencia de Dirección')),
                ('contactoNombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto de Emergencia')),
                ('contactoCelular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular de Contacto de Emergencia')),
                ('comprometido', models.BooleanField(default=False, verbose_name='¿Ha firmado el compromiso?')),
                ('tipoPref', models.CharField(choices=[('Diurna', 'Diurna'), ('Nocturna', 'Nocturna')], default='Diurna', max_length=20, verbose_name='Turno Preferido')),
                ('diaPref', models.CharField(choices=[('Semana', 'Día de Semana'), ('Fin de Semana', 'Fin de Semana')], default='Semana', max_length=20, verbose_name='Día de la semana Preferido')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='guardia_admin.area', verbose_name='Área')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='guardia_admin.cargo', verbose_name='Cargo')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='guardia_admin.contrato', verbose_name='Contrato')),
                ('depto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='guardia_admin.departamento', verbose_name='Departamento')),
                ('sedePref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferidos_sede', to='guardia_admin.sede', verbose_name='Sede Preferida')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Personal / Estudiante',
                'verbose_name_plural': 'Perfiles de Personal y Estudiantes',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
    ]
